language: rust
sudo: required
os:
- linux
rust:
- stable
services:
- docker
before_install:
- chmod +x build.sh
before_deploy: "./build.sh torchbear ${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: rutBnTY6mL5iOgG/4QdCsV1GJ8EL08hCWCqLlgLu0NOJ65owY1NaXocpj49C5Jw340ZXaAA2yumERIRRgbeOhBWEicUk6J5YPOOiLqDqc5f6fm7jfX7llZTqotNjp1LPN/NjShyjHp2ODhc4kNXXe6AAPbcXInakx4xPLoavKu1hAjG+LVekeX2k6LtUd+24e1xfjaoeg30hdaz+Q12SYeEtE7cFGmABW8rl8nerBAHS8c76i+n9lEBApckSpqASN6gD3bwPhzhBlLX72vlTezSzdeou9CfpZ1Px0/x2UaxoffdxMuRQi31JVEQ0reWtOoSJFNpm4oyP7LOZmms2LIsvGA/LxxFgXl3K5IfdRzO80TVGNz4k0IOWePipc3FEvey3DjwOg0InKAns3tyLHDj2sKw2N0js8af6kNhxorqdpPemT8YJPDPnxjIMkZDM7Mcqooit6PO2RTzlRVPdFwrZkcTZD96vaJHU01zcrayhthJPMLNwpMftAWWBKfrmokQhsIHpz+LNLmc6tPTBmTUP+JfrHS0zGqHVeoYHPPZZ4f+6l1Z6yKqqkN2B3O/iDuZaDGh3aDxxFCBooBuBAIvg4HLLIwLokUqX2DXngQjRMcg0RKlTLpj8I7BkBvMyMZrcVuYUl+507KPSIfuBVjsor7RJuoxDVw4ZYco=
  file_glob: true
  file: "torchbear-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    repo: foundpatterns/torchbear
    rust: stable
  
