language: rust
sudo: required
os:
- linux
rust:
- stable
services:
- docker
before_install:
- chmod +x build.sh
before_deploy: "./build.sh torchbear ${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: "fDqR+q8pGNUKso7QnYlkEI3Z7iSOu6knuxOqsHm7n+WSLUevO5xU4l2ZNVyk/2hmFI2MNCdyWWELwPWouBVGiyIwoaAbaw1ySuyaAl8huiL/ruNpXBU2scbMuFkUWjPiYSBskesr5Ia
rybaq+yZZVKEIA/ka0l5DTQWHAuDkHkrHLf2b21N5PUJl34RBkrWsTpf8U8g9zHez3bzE+FZ9vysTDAXVWdhW6TqNHdpMOlm1wpq5bi0cPdSQQhNMaYuuh0hZRcDC8Hk6ixjC1q/0wOYJ3kcDYXf5/
huLBr+kwHAgliv7dsRRJdDM0ILGfp6ip9jljQpXrUWan47oRyRNTZJVkjLL8jznMw6pZHKvywF8rLBUh3qPUfAobh/1Ym8X2iypwzwgftLZYAtpayrdISxMpXeniExFUO7ZzmIpqYYVcFYLZhwuP2d
xKqGiGxXpRcC4BtAcc4TWVx6cUYLrmEXZMHjb6uudwL/Wf2f6Oq87fQ2aCuZRMOzSL6i0khW/kQOjuFNfEqxLOGSzrCoaJH8vmgRLvR0Lfr0lWYPulT3dTib1YlzHaH4hUUOxnT5/8z2vxr80z2etT
GOGRaIir/iZja+Gp7+Pen2j06XoE2CVO/XLforuvov5Ku+QZ1/ODYfCQ9zEec3rTRKr1l1rj7pZvJlpoKe2tgkzGGI="
  file_glob: true
  file: "torchbear-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    repo: foundpatterns/torchbear
    rust: stable
  
