language: rust
sudo: required
os:
- linux
rust:
- stable
services:
- docker
before_install:
- chmod +x build.sh
before_deploy: "./build.sh torchbear ${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: "2nPKKZNcLBxxSeA1e9hdXVmVqQ3+1f8/1znSkedPZIixjvy5DQrDmMzYa6EPSZSUeL4mFaw+OgpDTcdpmbn2R8DBhQ8CFaMnA5nxGfEKVrqT/5fW0QlNbXDuBd0kbbrgJ9i8uxkkbA+
cz1q4Iy49JSfQJZUUtQVimgXemSIJLzXcFmKj5g/3nQVbnrrj4Do4ETj4OUyumT0Yuiok0XrS1EAcxoDFtg2r4VPVZEnn/nO/ErU6VyAr1aBPJmWVHTPIKtZQ1qw7C/8/lLSrYrxSMN8p+Zboc3PMw
J/27AI33TMNhJpiDPdRmOQP39X8/U8jvqMoCBqUpF2a9XDSVs96OX1zvQV9FWQjWZrcEwyklPWM4oSXxcz4UqL0KV5OHejB5Ih9NBSiIXJsn8gSA4rqcBQHMDsUxW8lFp2DW0F4sxeNCfMMYzhUunP
ZSRr8FU/znY2t0IHpXm11M+6w3CW/fQCYprTbMyZjqQxnwKkBmOSLzLLwcx1Xp8BQzTfKVwSOOWVqkKt7zgC/0xGA8ivGzqtduxlZAOyaLEbGcNO9bPNwK9grOJPDmVmpc+xGzJNbiFZXoru/B5Wbp
2eCwqVOnpp4lmoiJ4/xtdxL3EN0JkLdvUmCWNYkMOfDklpqOYfCj7DLvlJKf+Vt8OP7e0LhkshFY8BoOXaBVSpLiIY="
  file_glob: true
  file: "torchbear-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    repo: foundpatterns/torchbear
    rust: stable
  
