language: rust
sudo: required
os:
- linux
rust:
- stable
services:
- docker
before_install:
- chmod +x build.sh
before_deploy: "./build.sh torchbear ${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: "Qhk7UZV8v4z7rFqGf8sC46d4LV2C56Ix3gwYacsMibGGYz7xvIzOmSGSsA5Ce9r0uGzTd1MB2Y5RU5phGcM0MAtapuJM7MIlZYZ5BaYeoJQ/TTdDLUIJVZec8esnsQ96Y7i5u/Lzmhm
HWnTPD/J7l3HLyA50doD/gQ6/bOiV1ojDyAQdq6iwQKo6hFYAvJHxWsVD+VbhmO7Xfqlygnp4+J7Spv9BVVaPNF4XPu6X5z0oZ5/9OnS401ksjsYxh1Uh7hDEfzWi8mi6RnixDcvGPWHQ1UP5PRVMk
7tS1Pe6gOsSiRBFGfm6UhmasArENmk38fp9NLa28YkDZ9Y0tGN+JjVeAowRea/MNv6/y1cGOFoJoGPnrPtI90ltK9weUg97ytJUr44zWoORCxHNeuCQrlxHwfCzq5fmUTT+lbGdlpSrXyNoETvJCT0
CS/FewuQhCXjvyk4sBBvNROaxsyq+XLc80iDG6a66j5BJbR/a8qOMTN6xLT1Z49EvKFaZA2Cx/XI9zPF6SiEXifaAbbASNYuRp7lFz8Mx/vN3rwgwWM6bMjGFo6RjakOefe+tDddmGw7uzV2Hk4Z+j
f/XvLg9Amng0i3bQMHBgR5tCLHh66Jz1AysWHbOntjDGuzg5L6xpxE7get3/tUEm5lVuDqkd2qg7uAvsdhtIcVm2as="
  file_glob: true
  file: "torchbear-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    repo: foundpatterns/torchbear
    rust: stable
  
