language: rust
sudo: required
os:
- linux
rust:
- stable
services:
- docker
before_install:
- chmod +x build.sh
before_deploy: "./build.sh torchbear ${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: "IKeU0trVYGNvzaGJ/Y2RgmP92TC5xHm1XkEOw2fWbtQIuXLD0HV97dhJLLYHOBZAcjlgQEAfqfU8CPjF2v7q/YRIXW+BnsXUSQO0aQ5SPmiGYtT+ipLebnBXpgndixiSmSrF/G9UiBY
V99MIkSe60/iZ5Jn1lUlrNizWgYLAIV8YtsEzT6MFwbW/Se52jTEvfuJcb4OzsQ7X7autDICU69gPXKtztN9pnS2fMQHX0TQmy4nh68pliH6qZ3+8MTGCICihI60CcyB0Ifa6frg9PkjKP0eturYDq
nPP24bDJgBWIIaAar+3NYpictB2UEoz8ME5+k5GTI/4/FIXz1XIjjZTeePPAje4CGI6rjy7B+HqJ5MzcU/krBDdH9D/c7Wasm5/luPctQUXC4wyqAnUzx81XgNO7ast2WnoYSgWBhNSOcna9NTEJTa
hG9QWRERsbRHSm3kmnqXf5JxAQgOFRnRUQEi6Vi1wb6mdZlrW7HS+24aAv6YUKTGoOcm7mQWLlHW5ltv+73QAgo7Bl9g1Z4qryGeH0lCUOc7ubdU9zaGqO+vDeTVmP3CWdEtdKeW9nHU5sjsOHA+4E
cL9R6sD3I1d0qkyS87DAlT86fnqrltBPzoXEkeqUNTpe8XqJuduZ3H4pUicTvKrteMmUGyMSD/RxbxiK4/r0yZ8bm8="
  file_glob: true
  file: "torchbear-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    repo: foundpatterns/torchbear
    rust: stable
  
