[package]
name = "actix-lua-web"
version = "0.1.0"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]

[lib]
name = "torchbear_lib"
path = "src/lib.rs"

[[bin]]
name = "torchbear"
path = "src/main.rs"

[patch.crates-io]
openssl = { git = "https://github.com/ishitatsuyuki/rust-openssl", branch = "0.9.x" }

[dependencies]
actix = "0.7.3"
actix-web = "0.7.4"
actix-lua = "0.3.1"
futures = "0.1.23"
log = "0.4.5"
env_logger = "0.5.13"
tera = "0.11.12"
rlua = "0.14.2"
failure = "0.1.2"
failure_derive = "0.1.2"
serde = "1.0.75"
serde_yaml = "0.8.2"
rlua_serde = { git = "https://github.com/voidxnull/rlua_serde", branch = "update_rlua" }
uuid = "0.6.5"
serde_urlencoded = "0.5.3"
comrak = "0.2"
serde_json = "1.0.27"
rust_sodium = "0.10.0"
base64 = "0.9.2"
config = "0.9.0"
clap = "2.32.0"
chrono = "0.4"
fern = { version = "0.5", features = ["colored"] }