[package]
name = "actix_lua_http"
version = "0.1.0"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]

[dependencies]
actix = "0.7.3"
actix-web = "0.7.4"
actix-lua = "0.3.0"
futures = "0.1.23"
env_logger = "0.5.12"
