[package]
name = "actix_lua_http"
version = "0.1.0"
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]

[dependencies]
actix = "0.7.3"
actix-web = "0.7.4"
actix-lua = { git = "https://github.com/voidxnull/actix-lua", branch = "expose_vm" }
futures = "0.1.23"
env_logger = "0.5.12"
tera = "0.11.12"
rlua = "0.14.2"
failure = "0.1.2"
